# Linear regration of Life Expectancy Data

In [182]:
import pandas as pd

In [183]:
df=pd.read_csv('Life Expectancy Data.csv')

In [184]:
df.sample(6)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1792,Myanmar,2003,Developing,63.2,231.0,69,0.40,3.824212,8.0,830,...,86.0,1.97,78.0,0.5,219.782326,47624894.0,13.3,13.6,0.445,7.7
1663,Mauritania,2003,Developing,63.0,226.0,8,0.01,29.653709,NaN,3611,...,75.0,4.53,76.0,1.3,528.586613,2957117.0,1.3,1.1,0.447,6.6
615,Congo,2008,Developing,59.4,338.0,8,2.58,0.000000,73.0,2,...,77.0,2.90,79.0,4.3,NaN,NaN,8.4,8.0,0.527,10.0
619,Congo,2004,Developing,54.1,48.0,9,2.58,0.000000,NaN,3524,...,67.0,2.56,67.0,6.3,NaN,NaN,9.0,8.6,0.497,9.2
2571,Thailand,2013,Developing,74.5,153.0,9,6.50,788.687340,99.0,2641,...,99.0,4.00,99.0,0.1,6171.262444,6814365.0,7.9,7.9,0.733,13.6
1205,Indonesia,2012,Developing,68.5,183.0,129,0.08,254.468826,83.0,15489,...,84.0,2.90,83.0,0.3,3687.953996,248883232.0,1.5,1.4,0.669,12.6

In [185]:
df.columns = df.columns.str.strip()

In [186]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'under-five deaths', 'Polio', 'Total expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

In [187]:
df['Life expectancy']

0       65.0
1       59.9
2       59.9
3       59.5
4       59.2
        ...
2933    44.3
2934    44.5
2935    44.8
2936    45.3
2937    46.0
Name: Life expectancy, Length: 2938, dtype: float64

In [188]:
df['Status'].unique()

array(['Developing', 'Developed'], dtype=object)

In [189]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                448
Population                         652
thinness  1-19 years                34
thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64

In [190]:
df=df.drop('Country',axis=1)

In [191]:
df.shape

(2938, 21)

In [192]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.preprocessing import OrdinalEncoder

transform = ColumnTransformer(transformers=[
    ('tran1',
     SimpleImputer(),
    ['Adult Mortality','Alcohol','Hepatitis B','BMI','Polio', 'Total expenditure','Diphtheria', 'GDP', 'Population', 'thinness  1-19 years','thinness 5-9 years', 'Income composition of resources', 'Schooling']),
    ('tran2',OrdinalEncoder(categories=[['Developing','Developed']]),['Status'])
], remainder='passthrough')

In [193]:
from sklearn.model_selection import train_test_split

In [194]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('Life expectancy', axis=1),df['Life expectancy'],test_size=0.2,random_state=42)

In [195]:
x_train_trf = transform.fit_transform(x_train)

In [196]:
x_test_trf=transform.fit_transform(x_test)

In [198]:
x_test_trf[0]

array([1.23000000e+02, 9.70000000e-01, 8.30000000e+01, 4.85000000e+01,
       8.30000000e+01, 3.78000000e+00, 8.00000000e+00, 1.76224617e+03,
       1.89149770e+07, 6.40000000e+00, 6.30000000e+00, 6.36000000e-01,
       1.14000000e+01, 0.00000000e+00, 2.00600000e+03, 8.00000000e+00,
       1.22652333e+02, 5.17000000e+02, 1.00000000e+01, 1.00000000e-01])

In [199]:
transform.get_feature_names_out()

array(['tran1__Adult Mortality', 'tran1__Alcohol', 'tran1__Hepatitis B',
       'tran1__BMI', 'tran1__Polio', 'tran1__Total expenditure',
       'tran1__Diphtheria', 'tran1__GDP', 'tran1__Population',
       'tran1__thinness  1-19 years', 'tran1__thinness 5-9 years',
       'tran1__Income composition of resources', 'tran1__Schooling',
       'tran2__Status', 'remainder__Year', 'remainder__infant deaths',
       'remainder__percentage expenditure', 'remainder__Measles',
       'remainder__under-five deaths', 'remainder__HIV/AIDS'],
      dtype=object)

In [200]:
columns = [
    'Adult Mortality',
    'Alcohol',
    'Hepatitis B',
    'BMI',
    'Polio',
    'Total expenditure',
    'Diphtheria',
    'GDP',
    'Population',
    'thinness  1-19 years',
    'thinness 5-9 years',
    'Income composition of resources',
    'Schooling',
    'Status',
    'Year',
    'infant deaths',
    'percentage expenditure',
    'Measles',
    'under-five deaths',
    'HIV/AIDS'
]

In [201]:
x_train_trf = pd.DataFrame(
    transform.fit_transform(x_train),
    columns=columns,
    index=x_train.index
)

In [203]:
x_test_trf = pd.DataFrame(
    transform.fit_transform(x_test),
    columns=columns,
    index=x_test.index
)

In [204]:
x_train_trf.isnull().sum()

Adult Mortality                    0
Alcohol                            0
Hepatitis B                        0
BMI                                0
Polio                              0
Total expenditure                  0
Diphtheria                         0
GDP                                0
Population                         0
thinness  1-19 years               0
thinness 5-9 years                 0
Income composition of resources    0
Schooling                          0
Status                             0
Year                               0
infant deaths                      0
percentage expenditure             0
Measles                            0
under-five deaths                  0
HIV/AIDS                           0
dtype: int64

In [205]:
x_test_trf.isnull().sum()

Adult Mortality                    0
Alcohol                            0
Hepatitis B                        0
BMI                                0
Polio                              0
Total expenditure                  0
Diphtheria                         0
GDP                                0
Population                         0
thinness  1-19 years               0
thinness 5-9 years                 0
Income composition of resources    0
Schooling                          0
Status                             0
Year                               0
infant deaths                      0
percentage expenditure             0
Measles                            0
under-five deaths                  0
HIV/AIDS                           0
dtype: int64

In [206]:
x_train.columns

Index(['Year', 'Status', 'Adult Mortality', 'infant deaths', 'Alcohol',
       'percentage expenditure', 'Hepatitis B', 'Measles', 'BMI',
       'under-five deaths', 'Polio', 'Total expenditure', 'Diphtheria',
       'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

In [207]:
lr=LinearRegression()

In [208]:
x_train_trf.head()

,Adult Mortality,Alcohol,Hepatitis B,BMI,Polio,Total expenditure,Diphtheria,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Status,Year,infant deaths,percentage expenditure,Measles,under-five deaths,HIV/AIDS
456,126.0,5.28,96.000000,25.5,98.0,4.30,98.0,3112.285712,4.864380e+05,8.1,8.0,0.602,11.9,0.0,2007.0,0.0,345.463714,0.0,0.0,0.6
462,152.0,3.81,81.141811,22.1,91.0,5.19,9.0,1268.884564,4.437160e+05,9.4,9.3,0.562,11.0,0.0,2001.0,0.0,150.743486,0.0,0.0,0.8
2172,143.0,10.43,99.000000,44.5,99.0,7.58,99.0,7384.623471,1.192254e+07,4.3,4.3,0.733,12.9,0.0,2011.0,0.0,0.000000,0.0,0.0,0.1
2667,13.0,1.29,98.000000,59.3,98.0,7.26,98.0,4199.472530,1.114558e+06,6.4,6.3,0.720,14.7,0.0,2013.0,3.0,594.645310,16.0,3.0,0.1
381,95.0,0.13,99.000000,28.0,99.0,3.40,94.0,16846.219800,1.192254e+07,6.7,6.1,0.820,13.3,0.0,2002.0,0.0,941.703687,0.0,0.0,0.1

In [209]:
x_train_trf[ 'under-five deaths']

456      0.0
462      0.0
2172     0.0
2667     3.0
381      0.0
        ...
1638     0.0
1095     7.0
1130    23.0
1294     3.0
860      9.0
Name: under-five deaths, Length: 2350, dtype: float64

In [210]:
x_train_trf.columns

Index(['Adult Mortality', 'Alcohol', 'Hepatitis B', 'BMI', 'Polio',
       'Total expenditure', 'Diphtheria', 'GDP', 'Population',
       'thinness  1-19 years', 'thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Status', 'Year',
       'infant deaths', 'percentage expenditure', 'Measles',
       'under-five deaths', 'HIV/AIDS'],
      dtype='object')

In [216]:
y_train.isnull().sum()

np.int64(8)

In [226]:
y_test.isnull().sum()

np.int64(2)

In [227]:
y_test = y_test.fillna(y_test.mean())

In [228]:
y_train = y_train.fillna(y_train.mean())

In [229]:
lr.fit(x_train_trf,y_train)

LinearRegression()

In [230]:
y_pred=lr.predict(x_test_trf)

# All the Matrics of the Model

In [231]:
r2=r2_score(y_test,y_pred)

In [232]:
r2

0.8243117626647224

In [233]:
mae=mean_absolute_error(y_test,y_pred)

In [234]:
mae

2.8578520700765906

In [235]:
mse=mean_squared_error(y_test,y_pred)

In [236]:
mse

15.220773146485962